
parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    - jsx

rules:
  indent:
    - 2
    - 2
  quotes:
    - 2
    - single
  semi:
    - 2
    - always
env:
  es6: true
  browser: false
  node: true

extends: 'eslint:recommended'
